server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/uniclub}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:huytran123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# cấu hình email
sendgrid:
  api-key: ${SENDGRID_API_KEY:your-sendgrid-api-key-here}
app:
  mail:
    from: "no-reply@mail.tranhuy.dev"      # Phải là email hợp lệ (có @)
    otp-expiration-minutes: 5              # mã OTP hết hạn sau 5 phút
    max-attempts: 5

jwt:
  secret: uniclub-secret-key-for-jwt-token-generation-2024
  expiration: 86400000  # 24 hours in milliseconds

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:deooamndi}
  api_key: ${CLOUDINARY_API_KEY:186558834811161}
  api_secret: ${CLOUDINARY_API_SECRET:7iKsQDdlEz-vPTEYyuePBiET7Sw}